apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  type: NodePort
  selector:
    app: myapp
    release: canary
  ports:
    - name: redis
      port: 80
      targetPort: 80
      nodePort: 30080
