apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
      - name: http
        containerPort: 80
      - name: https
        containerPort: 443
    volumeMounts:
      - name: html
        mountPath: /data/web/html/
  - name: busybox
    image: busybox:latest
    volumeMounts:
      - name: html
        mountPath: /data/
    command: ['/bin/sh','-c',"while true ; do echo $(date) >> /data/index.html ; sleep 2; done"]
    # command: ['/bin/sh','-c',"sleep 3500"]
  volumes:
    - name: html
      emptyDir: {}
