apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: redis
    role: logstor
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
