# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc001
#   namespace: default
# spec:
#   accessModes: ["ReadWriteOnce"]
#   storageClassName: state-pvc001
#   resources:
#     requests:
#       storage: 6Gi
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
    - port: 80
      name: web
      targetPort: 80
  clusterIP: None
  selector:
    app: myapp-pod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  serviceName: myapp
  replicas: 3
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
        - name: myapp
          image: ikubernetes/myapp:v5
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: myappdata
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: myappdata
      spec:
        accessModes: ["ReadWriteOnce","ReadWriteMany"]
        storageClassName: state-pvc001
        resources:
          requests:
            storage: 2Gi
