apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: Null
  name: pods-reader
rules:
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
