FROM centos:centos7.5.1804
LABEL maintainer="<yousong.xiang@xuncetech.com>" \
      name="cplus" \
      author="youxong.xiang" \
      vendor="xunce" \
      version="v0.0.1" \
      systemver="Centos7.5" \
      desc="c++ docker" \
      build-date="20201123"
# SET ENVIRONNEMENT
ENV LANG=zh_CN.UTF-8 \
    LANGUAGE=zh_CN.UTF-8 \
    TIME_ZONE=Asia/Shanghai

#COPY Resources /tmp/Resources

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&\
    yum-config-manager --add-repo http://mirrors.aliyun.com/repo/Centos-7.repo &&\
    yum-config-manager --add-repo http://mirrors.xuncetech.com/xunce/xunce-dev/yum/el7/xunce-dev.repo &&\
    yum-config-manager --add-repo http://mirrors.xuncetech.com/mysql-repo/yum/mysql-8.0-community/el/7/mysql-8.0-community.repo &&\
    yum install -y epel-release yum-plugin-fastestmirror vim-enhanced wget bash-completion elinks dos2unix git openssl-devel libuv-devel\
    sudo vim which automake autoconf autogen libtool gettext-devel libcurl-devel unixODBC-devel &&\
    yum install -y --enablerepo=xunce-dev \
        tinyxml2-7.0.0 \
        xlslib-2.4.0 \
        cmake-3.12.3 \
        boost169-1.69 \
        freetds-R1_00RC5 \
        jsoncpp-1.8.4 \
        spdlog-1.1.0 \
        uWebSockets-0.14.10\
        hiredis-0.14.0 \
        protobuf-3.6.1 \
        libzmq-4.2.5 \
        sqlite-devel-3.7.17 \
        zookeeper-client-3.5.5 \
        hiredis-vip-1.0.0\
        oracle-instantclient11.2-basic-11.2.0.4.0 \
        oracle-instantclient11.2-dummy-1.0 \
        oracle-instantclient11.2-devel-11.2.0.4.0 \
        librdkafka \
        QuantLib-1.16 \
        libuuid-devel \
        glog-devel-0.3.3 \
        yaml-cpp-0.6.3 &&\
    yum install -y --enablerepo=mysql80-community \
        mysql-community-devel &&\
    echo "/usr/lib/oracle/11.2/client64/lib">>/etc/ld.so.conf.d/oracle.conf &&\
    yum clean all && ldconfig

EXPOSE 11000
USER root
CMD ["/usr/sbin/init"]
