apiVersion: v1
kind: Pod
metadata:
  name: pod-sa-demo
  namespace: default
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    imagePullPolicy: Always
    ports:
    - name: https
      containerPort: 443
    - name: http
      containerPort: 80
  serviceAccountName: admin
