FROM centos:centos7.5.1804
LABEL maintainer="<yousong.xiang@xuncetech.com>" \
      name="vone-deploy" \
      author="yousong.xiang" \
      version="v1.0.1" \
      systemver="Centos7.6" \
      desc="vone java depoy" \
      build-date="2020.10.16"

#COPY xone-dev-source/java/RPM /tmp/RPM

#安装jdk java-1.8.0-openjdk java-1.8.0-openjdk-devel
RUN set -ex; \
    \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    #cd /tmp/RPM; \
    #tar -zxf jdk.tar.gz; \
    #yum localinstall -y *rpm; \
    yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel net-tools; \
    #获取jdk版本目录
    jdk_version=`ls /usr/lib/jvm |grep "java-1.8.0-openjdk.*x86_64"|head -1`; \
    echo "export JAVA_HOME=/usr/lib/jvm/${jdk_version}" >>/root/.bashrc; \
    source /root/.bashrc; \
    #rm -rf /tmp/RPM; \
    yum clean all

USER root

CMD ["/usr/sbin/init"]
