FROM centos:centos7.6.1810
LABEL maintainer="<yousong.xiang@xuncetech.com>" \
      name="vone-deploy" \
      author="yousong.xiang" \
      version="v1.0.1" \
      systemver="Centos7.6" \
      desc="vone java depoy" \
      build-date="2020.10.16"

ENV LANG=zh_CN.UTF-8 \
    LANGUAGE=zh_CN.UTF-8 \
    TIME_ZONE=Asia/Shanghai \
    JAVA_HOME=/usr/lib/jvm/java-1.8.0

#安装jdk java-1.8.0-openjdk java-1.8.0-openjdk-devel
RUN localedef -v -c -i en_US -f UTF-8 zh_CN.UTF-8 >/dev/null 2>&1; \
    set -ex; \
    \
    grep -q 'zh_CN.utf8' /etc/locale.conf || sed -i -E 's/^LANG=.*/LANG="zh_CN.UTF-8"/' /etc/locale.conf; \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel net-tools; \
    yum clean all

USER root

CMD ["/usr/sbin/init"]
