FROM centos:centos7.5.1804 as prep
LABEL maintainer="<yousong.xiang@xuncetech.com>" \
      name="rpmbuild" \
      author="yousong.xiang" \
      version="v1.0.1" \
      systemver="Centos7.5" \
      desc="xone_c++ devtoolset" \
      build-date="20190103"

COPY xone-dev-source/app /tmp/app

#安装gcc 4.8
RUN set -ex; \
    \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    cd /tmp/app; \
    tar -zxf gcc.tar.gz; \
    yum localinstall -y *rpm

#编译java程序xlslib
RUN set -ex; \
    \
    cd /tmp/app; \
    tar -zxf cpp.tar.gz; \
    cd cpp; \
    tar -zxf xlslib-2.4.0.tar.gz; \
    cd xlslib-2.4.0; \
    ./configure --prefix=/usr; \
    make && make install; \
    yum clean all


#基础build环境
FROM centos:centos7.5.1804


COPY xone-dev-source/app /tmp/app
#COPY src /tmp/src

RUN set -ex; \
    \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    cd /tmp/app; \
    tar -zxf devtoolset-cpp.tar.gz; \
    tar -zxf libtool.tar.gz; \
    tar -zxf openssl-devel.tar.gz; \
    tar -zxf boost-dev.tar.gz; \
    tar -zxf libcurl-dev.tar.gz; \
    tar -zxf libuuid-dev.tar.gz; \
    tar -zxf libuv-dev.tar.gz; \
    tar -zxf mysql-dev.tar.gz; \
    yum localinstall -y *rpm; \
    scl enable devtoolset-7 bash; \
    echo "source /opt/rh/devtoolset-7/enable" >> /root/.bashrc; \
    source /root/.bashrc; \
    yum clean all


RUN set -ex; \
    \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    source /root/.bashrc; \
    cd /tmp/app; \
    tar -zxf cpp.tar.gz; \
    cd cpp; \
    tar -zxf libzmq-4.2.1.tar.gz; \
    cd libzmq-4.2.1; \
    ./autogen.sh; \
    ./configure --prefix=/usr; \
    make && make install; \
    \
    cd ..; \
    tar -zxf hiredis-0.14.0.tar.gz; \
    cd hiredis-0.14.0; \
    make && make install; \
    \
    cd ..; \
    tar -zxf cmake-3.12.3.tar.gz; \
    cd cmake-3.12.3; \
    ./bootstrap; \
    make && make install; \
    \
    cd ..; \
    tar -zxf jsoncpp-1.8.0.tar.gz; \
    cd jsoncpp-1.8.0; \
    cmake -DCMAKE_BUILD_TYPE=release -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/ .; \
    make && make install; \
    \
    cd ..; \
    tar -zxf tinyxml2-7.0.0.tar.gz; \
    cd tinyxml2-7.0.0; \
    cmake -DCMAKE_INSTALL_PREFIX=/usr; \
    make && make install; \
    cd ..; \
    \
    tar -zxf protobuf-3.10.1.tar.gz; \
    cd protobuf-3.10.1; \
    ./autogen.sh; \
    ./configure; \
    make && make install; \
    cd ..; \
    \
    tar -zxf spdlog-1.1.0.tar.gz; \
    cd spdlog-1.1.0; \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/ .; \
    make && make install; \
    cd ..; \
    \
    tar -xzf uWebSockets-0.14.10.tar.gz; \
    cd uWebSockets-0.14.10; \
    cmake .; \
    make && make install; \
    cd ..; \
    \
    tar -zxf QuantLib-1.16.tar.gz; \
    cd QuantLib-1.16; \
    ./configure --prefix=/usr; \
    make && make install

#RUN set -ex; \
#    \
#    cd /tmp/src/cpp; \
#    cmake ./; \
#    make; \
#    make install; \
#    \
#    echo "/usr/lib/uvframe" >> /etc/ld.so.conf.d; \
#    echo "/usr/lib/uvframe/thirdparty" >> /etc/ld.so.conf.d; \



RUN set -ex; \
    \
    groupadd -g 5002 opadm; \
    useradd -u 5002 -g opadm -G wheel  -d /home/opadm -m -s /bin/bash opadm

USER root
#WORKDIR /home/opadm

CMD ["/usr/sbin/init"]
