FROM xiangys0134/xone-app-dev:v1.0.1 as build
LABEL maintainer="<yousong.xiang@xuncetech.com>" \
      name="rpmbuild" \
      author="yousong.xiang" \
      version="v1.0.1" \
      systemver="Centos7.5" \
      desc="xone_c++ devtoolset" \
      build-date="20190103"

#COPY xone-dev-source/app /tmp/app
COPY src /tmp/src

#安装gcc 4.8
RUN set -ex; \
    \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    cd /tmp/src/cpp; \
    source /root/.bashrc; \
    ldconfig; \
    cmake ./; \
    make -j4; \
    make install; \
    \
    echo "/usr/lib/uvframe" >> /etc/ld.so.conf.d/uvframe.conf; \
    echo "/usr/lib/uvframe/thirdparty" >> /etc/ld.so.conf.d/uvframe.conf; \
    \
    rm -rf /tmp/src

# docker部署环境
FROM xiangys0134/xone-app-deploy:v1.0.1

#cpp
COPY --from=build /etc/ld.so.conf.d /etc/ld.so.conf.d
COPY --from=build /usr/bin/uvframe /usr/bin/uvframe
COPY --from=build /usr/lib/uvframe /usr/lib/uvframe
COPY --from=build /etc/uvframe /etc/uvframe


RUN set -ex; \
    \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    groupadd -g 5002 opadm; \
    useradd -u 5002 -g opadm -G wheel  -d /home/opadm -m -s /bin/bash opadm; \
    mkdir -p /home/frame/logs; \
    chown -R opadm:opadm /home/frame; \
    ldconfig

USER opadm
WORKDIR /home/opadm

CMD ["/usr/sbin/init"]
