#
# 描述: c++基础编译镜像
#
# github：https://github.com/xiangys0134/Dockerfile/blob/xone-java-dev-v1.0.4/dockerfile/XONE/Dockerfile_c%2B%2B
#
# github镜像地址：xiangys0134/xone-app-dev
#
FROM centos:centos7.5.1804


COPY xone-dev-source/app /tmp/app

#基础依赖组件
# - devtoolset-7-gcc 7.3.1
# - devtoolset-7-gcc-c++ 7.3.1
# - devtoolset-7-make 4.2.1
# - libzmq  4.2.1
# - hiredis  0.14.0
# - jsoncpp  1.8.0
# - tinyxml2  7.0.0
# - protobuf  3.10.1
# - xlslib  2.4.0
# - spdlog  1.1.0
# - uWebSockets  0.14.9
# - QuantLib  1.16
# - cmake  3.12.3

RUN set -ex; \
    \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    cd /tmp/app; \
    tar -zxf devtoolset-cpp.tar.gz; \
    tar -zxf libtool.tar.gz; \
    tar -zxf openssl-devel.tar.gz; \
    tar -zxf boost-dev.tar.gz; \
    tar -zxf libcurl-dev.tar.gz; \
    tar -zxf libuuid-dev.tar.gz; \
    tar -zxf libuv-dev.tar.gz; \
    tar -zxf mysql-dev.tar.gz; \
    tar -zxf file.tar.gz; \
    yum localinstall -y *rpm; \
    scl enable devtoolset-7 bash; \
    echo "source /opt/rh/devtoolset-7/enable" >> /root/.bashrc; \
    source /root/.bashrc; \
    sed -i '1034s/[<>]/"/g' /usr/include/mysql/mysql_com.h; \
    yum clean all


RUN set -ex; \
    \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    source /root/.bashrc; \
    cd /tmp/app; \
    tar -zxf cpp.tar.gz; \
    cd cpp; \
    tar -zxf xlslib-2.4.0.tar.gz; \
    cd xlslib-2.4.0; \
    sed -i '80s/CCLD/CXXLD/' ./targets/test/Makefile.in; \
    ./configure --prefix=/usr; \
    make && make install; \
    cd ..; \
    \
    tar -zxf libzmq-4.2.1.tar.gz; \
    cd libzmq-4.2.1; \
    ./autogen.sh; \
    ./configure --prefix=/usr; \
    make && make install; \
    \
    cd ..; \
    tar -zxf hiredis-0.14.0.tar.gz; \
    cd hiredis-0.14.0; \
    make && make install; \
    \
    cd ..; \
    tar -zxf cmake-3.12.3.tar.gz; \
    cd cmake-3.12.3; \
    ./bootstrap; \
    make && make install; \
    \
    cd ..; \
    tar -zxf jsoncpp-1.8.0.tar.gz; \
    cd jsoncpp-1.8.0; \
    cmake -DCMAKE_BUILD_TYPE=release -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/ .; \
    make && make install; \
    \
    cd ..; \
    tar -zxf tinyxml2-7.0.0.tar.gz; \
    cd tinyxml2-7.0.0; \
    cmake -DCMAKE_INSTALL_PREFIX=/usr; \
    make && make install; \
    cd ..; \
    \
    tar -zxf protobuf-3.10.1.tar.gz; \
    cd protobuf-3.10.1; \
    ./autogen.sh; \
    ./configure --prefix=/usr; \
    make && make install; \
    cd ..; \
    \
    tar -zxf spdlog-1.1.0.tar.gz; \
    cd spdlog-1.1.0; \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/ .; \
    make && make install; \
    cd ..; \
    \
    tar -xzf uWebSockets-0.14.10.tar.gz; \
    cd uWebSockets-0.14.10; \
    cmake .; \
    make && make install; \
    cd ..; \
    \
    tar -zxf QuantLib-1.16.tar.gz; \
    cd QuantLib-1.16; \
    ./autogen.sh; \
    ./configure --prefix=/usr; \
    make && make install; \
    rm -f /usr/lib/libQuantLib.a; \
    \
    cd ..; \
    rm -rf /tmp/app



#RUN set -ex; \
#    \
#    groupadd -g 5002 opadm; \
#    useradd -u 5002 -g opadm -G wheel  -d /home/opadm -m -s /bin/bash opadm

USER root

CMD ["/usr/sbin/init"]
