version: "3"
services:
  xone-dev-rpm:
    image: xiangys0134/xc_devtool_xone:xone-java-dev-rpm-v0.1
    container_name: xone-dev-rpm
    restart: always
    privileged: true
    entrypoint: ["/bin/sh","/usr/local/bin/jenkins.sh"]
    environment:
      - JENKINS_URL=http://jenkins:8080/computer/xone-dev-rpm/slave-agent.jnlp
      - JENKINS_SECRET=27a798cb84369b00c24b81138aaca4404b384b4a7ae7d1a295a1d540d104d1e3
      - JENKINS_AGENT_WORKDIR=/data/jenkins_home
      - JENKINS_USER=root
    networks:
      - xunce
networks:
  xunce:
